FROM agrigorev/zoomcamp-model:2025

WORKDIR /app

COPY pyproject.toml .

RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root \
    && pip install "uvicorn[standard]"

COPY predict_api.py .

EXPOSE 9696

CMD ["uvicorn", "predict_api:app", "--host", "0.0.0.0", "--port", "9696"]
